### ISSUE TITLE
Diseño del layout lista

### ISSUE THREAD

**Issue by SrRodavlas** [SrRodavlas/ToDo_Ocio#2]
Decidir como sera el aspecto del activity lista y los componentes que contendrá la pantalla con sus nombres de identificación.

**Comment by RbnAv** [comment]
Los nombres de los elementos en esta activity son:
lst_categorias
btn_nuevo (este es el botón flotante)
btn_ver
btn_buscar
vsb_scroll

**Comment by RbnAv** [comment]
![img_20180212_122932](https://user-images.githubusercontent.com/22275095/36158654-1e83f11c-10dd-11e8-9880-8503fa71e07e.jpg)
