### ISSUE TITLE
Diseño del layout ver

### ISSUE THREAD

**Issue by SrRodavlas** [SrRodavlas/ToDo_Ocio#3]
Decidir como sera el aspecto del layout ver y los componentes que contendrá la pantalla con sus nombres de identificación.

**Comment by RbnAv** [comment]
Los nombres de los elementos en esta activity son:
btn_editar
btn_borrar
lbl_vNombre
lbl_vBio
mpv_vLocalizacion
img_vFoto

**Comment by RbnAv** [comment]
![img_20180212_122932](https://user-images.githubusercontent.com/22275095/36158694-34176b76-10dd-11e8-950c-10fddaae3901.jpg)
