### ISSUE TITLE
Implementar uso de la cámara

### ISSUE THREAD

**Issue by RbnAv** [SrRodavlas/ToDo_Ocio#32]
Hacer que se puedan tomar fotografias desde la aplicación.

**Comment by SrRodavlas** [comment]
Tras investigar un poco ya he conseguido tomar fotos desde la cámara y insertar la imagen en la galería de Android.
![image](https://user-images.githubusercontent.com/32173236/36940545-2ced6a50-1f45-11e8-8c3f-468dd8169a69.png)
![image](https://user-images.githubusercontent.com/32173236/36940548-3fca68c6-1f45-11e8-8808-c2b310ffc91d.png)
![image](https://user-images.githubusercontent.com/32173236/36940563-9a138c9a-1f45-11e8-8e9f-9ba86bbad320.png)
![image](https://user-images.githubusercontent.com/32173236/36940564-a2c64436-1f45-11e8-989e-a523f2d402ed.png)

**Comment by RbnAv** [comment]
El código tenía una interface implementada para poder utilizar los cuadros de diálogos  para la cámara y la galería. Ahora con los dos botones no sirve de nada y habrá que eliminarlo para limpiar un poco.
