### ISSUE TITLE
Diseño del layout editar

### ISSUE THREAD

**Issue by SrRodavlas** [SrRodavlas/ToDo_Ocio#4]
Decidir como sera el aspecto del layout editar y los componentes que contendrá la pantalla con sus nombres de identificación.

**Comment by RbnAv** [comment]
Los nombres de los elementos en esta activity son:
lbl_lugar
txt_lugar --> (textfield)
lbl_bio
txt_bio --> (textarea)
mpv_localizacion
btn_guardar

**Comment by RbnAv** [comment]
![img_20180212_122932](https://user-images.githubusercontent.com/22275095/36158715-418777a6-10dd-11e8-952d-214338953401.jpg)
