### ISSUE TITLE
Diseño del layout mapa

### ISSUE THREAD

**Issue by SrRodavlas** [SrRodavlas/ToDo_Ocio#5]
Decidir como sera el aspecto del layout mapa y los componentes que contendrá la pantalla con sus nombres de identificación.

**Comment by RbnAv** [comment]
Los nombres de los elementos en esta activity son:
chk_cine
chk_parques
chk_restaurantes
mpv_mapa

**Comment by RbnAv** [comment]
![img_20180212_122932](https://user-images.githubusercontent.com/22275095/36158729-4abb4d5c-10dd-11e8-9e6a-0c3818f20537.jpg)

Aparece girada por algún motivo
