### ISSUE TITLE
Diseño de la base de datos

### ISSUE THREAD

**Issue by SrRodavlas** [SrRodavlas/ToDo_Ocio#6]
Decidir como sera la estructura de la base de datos. Las tablas que contiene y que campos necesarios para almacenar los datos de la lista de lugares.

**Comment by luisaoprog** [comment]
Ya se ha creado el modelo ER de la base de datos que se muestra a continuación:
![diagrama1](https://user-images.githubusercontent.com/29001841/36147906-5bffced0-10ba-11e8-95d8-2e6c9feb2a8c.png)
