### ISSUE TITLE
Implementación del layout lista

### ISSUE THREAD

**Issue by SrRodavlas** [SrRodavlas/ToDo_Ocio#7]
Implementar la interfaz del activity lista en la aplicación y será la pantalla principal(por defecto). Necesita que la tarea #2 este completada para proceder con esta.

**Comment by RbnAv** [comment]
![captura de pantalla 8](https://user-images.githubusercontent.com/22275095/36149563-7ca5e72c-10c0-11e8-84b4-53a5afe9fed2.png)
